name: flutgpt
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  build_runner: ^2.3.3
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  flutter_localizations:
    sdk: flutter
  flutter_tts: ^3.6.3
  get: ^4.6.5
  google_fonts: ^4.0.1
#  hive: ^2.2.3
#  hive_flutter: ^1.1.0
#  hive_generator: ^2.0.0
  http: ^0.13.5
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  path: ^1.8.2
  path_provider: ^2.0.14
  sembast: ^3.4.3+1
  speech_to_text: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: "chatgpt_logo"
  ios: true
  image_path: "assets/chatgpt_logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
